spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/orders
    username: root
    password: MangCau1988@@



  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true