spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: root
    password: MangCau1988@@
    driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update